namespace Syslog.Extensions.Logging
{
    public enum FacilityType
    {
        Kern,
        User,
        Mail,
        Daemon,
        Auth,
        Syslog,
        LPR,
        News,
        UUCP,
        Cron,
        AuthPriv,
        FTP,
        NTP,
        Audit,
        Audit2,
        CRON2,
        Local0,
        Local1,
        Local2,
        Local3,
        Local4,
        Local5,
        Local6,
        Local7
    }
}